//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Resource.rc에서 사용되고 있습니다.
//
#define IDD_BUSINESSCARDBINDERFORM      101
#define IDD_TAKINFORM                   103
#define IDC_GROUP_BISINESSCARD          1001
#define IDC_GROUP_PERSONAL              1002
#define IDC_GROUP_COMPANY               1003
#define IDC_STATIC_PERSONALNAME         1004
#define IDC_STATIC_PERSONALPOSITION     1005
#define IDC_STATIC_PERSONALCELLULARPHONENUMBER 1006
#define IDC_STATIC_PERSONALEMAILADDRESS 1007
#define IDC_BUTTON_TAKEIN               1009
#define IDC_BUTTON_FIRST                1010
#define IDC_EDIT_PERSONALNAME           1011
#define IDC_STATIC_COMPANYNAME          1012
#define IDC_STATIC_COMPANYTELEPHONENUMBER 1013
#define IDC_STATIC_COMPANYURL           1014
#define IDC_STATIC_COMPANYADDRESS       1015
#define IDC_EDIT_PERSONALCELLUALRPHONENUMBER 1016
#define IDC_EDIT_PERSONALEMAILADDRESS   1017
#define IDC_COMBO_PERSONALPOSITION      1018
#define IDC_STATIC_PERSONALEMAIL        1019
#define IDC_STATIC_COMPANYFAXNUMBER     1020
#define IDC_COMBO_PERSONALEMAILADDRESS  1021
#define IDC_STATIC_PERSONALNAME_INFO    1022
#define IDC_EDIT_COMPANYNAME            1022
#define IDC_STATIC_PERSONALPOSITION_INFO 1023
#define IDC_EDIT_COMPANYTELEPHONENUMBER 1023
#define IDC_STATIC_PERSONALCELLULARPHONENUMBER_INFO 1024
#define IDC_EDIT_COMPANYURL             1024
#define IDC_STATIC_PERSONALEMAILADDRESS_INFO 1025
#define IDC_EDIT_COMPANYADDRESS         1025
#define IDC_STATIC_COMPANYNAME_INFO     1026
#define IDC_EDIT_COMPANYADDRESS2        1026
#define IDC_EDIT_COMPANYFAXNUMBER       1026
#define IDC_STATIC_COMPANYTELEPHONENUMBER_INFO 1027
#define IDC_STATIC_COMPANYURL_INFO      1028
#define IDC_STATIC_COMPANYADDRESS_INFO  1029
#define IDC_STATIC_COMPANYFAXNUMBER_INFO 1030
#define IDC_BUTTON_FIND                 1031
#define IDC_BUTTON_TAKEOUT              1032
#define IDC_BUTTON_ARRANGE              1033
#define IDC_BUTTON_PREVIOUS             1034
#define IDC_BUTTON_NEXT                 1035
#define IDC_BUTTON_LAST                 1036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
